version: '3'
services:
  app:
    # ComposeFileを実行してビルドされるときのパスを指定
    build:
      context: .
      dockerfile: Dockerfile_prd
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    # マウントする設定ファイルのパスを指定
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: production
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
