version: '3'
services:
  db:
    image: postgres
     # dbにマウントする設定ファイルのパスを指定
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    # ComposeFileを実行してビルドされるときのパスを指定
    build:
      context: .
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    # マウントする設定ファイルのパスを指定
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    depends_on:
      # webというServiceの前に、db、chromeというServiceを実行する
      - db
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
